### ISSUE TITLE
📃: Add Personal Blog Project

### ISSUE THREAD

**Issue by adwityac** [iamrahulmahato/master-web-development#1003]
🔴 **Title**: Personal Blog Project

🔴 **Tech stack**: HTML, CSS, JavaScript

🔴 **Objective**: To create a simple personal blog where users can read posts, learn about the author, and contact them.

🔴 **Summary**: This project involves building a personal blog website with a home page displaying blog posts, an "About" page with information about the author, and a "Contact" page with a form for users to reach out. The website is designed to be user-friendly and visually appealing, providing a platform for sharing thoughts and experiences.

📸 **Screenshots**  
![Screenshot of Personal Blog](https://i.ibb.co/JKgXdkV/Screenshot-2024-10-11-190612.png)

***********************************************************************

✅ **Details to Include When Taking the Issue:**  
**Name**: Adwitya Chakraborty
**Participant Role**: GSSOC (Contributor)

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by swarupsahu08** [comment]
Hey   @iamrahulmahato Can you assign me this issue

**Comment by Avansh2006** [comment]
Hii @iamrahulmahato !!
I have read your requirements and I can help you in creating the webpage, since I already have experience of working on the same type of project. I can create the blog page backend or if you want I can also create it with local storage (browser storage).
Please assign me this issue so that I can start working on the project...
